WRKDIRPREFIX=/tmp

# global SET/UNSET examples
OPTIONS_UNSET+=DOCS
OPTIONS_UNSET+=EXAMPLES
OPTIONS_UNSET+=TESTS
OPTIONS_UNSET+=NLS
OPTIONS_UNSET+=DEBUG
OPTIONS_UNSET+=HELP
OPTIONS_UNSET+=INFO
OPTIONS_UNSET+=MAN
OPTIONS_UNSET+=MAN3
OPTIONS_UNSET+=MANPAGES
OPTIONS_UNSET+=X11

OPTIONS_SET+=OPTIMIZED_CFLAGS

# per-port examples:
# 1)
#if ${.CURDIR:M*/www/mod_php86}
#CONFIGURE_ENV+= pthreads_working="yes"
#OPTIONS_SET+=OPTIMIZED_CFLAGS
#.endif
# 2)
#.if ${.CURDIR:N*devel/cloudabi-toolchain*} == ""
#DEFAULT_VERSIONS+=llvm=10
#.endif
